language: python

python:
  - 2.7

services: mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=tola.settings.local
  - export PYTHONPATH=$HOME/builds/mercycorps/TolaActivity
  - export PIP_USE_MIRRORS=true
  - mysql -e 'CREATE DATABASE tola_activity;'

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate --noinput
  - python manage.py test
