ADMINS:
 -
   - "admin"
   - "toladata@mercycorps.org"

ALLOWED_HOSTS:
 - "127.0.0.1"
 - "localhost"
 - "www.mercycorps.org"
 - "www.google.com"
 - "*.github.com"
 - "www.github.com"
 - "api.github.com"
 - "tola-activity-dev.mercycorps.org"
 - "tola-activity-demo.mercycorps.org"
 - "tola-activity.mercycorps.org"
 - "tola-tables.mercycorps.org"

EMAIL_USE_TLS: True
EMAIL_HOST: 'smtp.gmail.com'
EMAIL_PORT: 587
EMAIL_HOST_USER: 'systems@mercycorps.org'
EMAIL_HOST_PASSWORD: 'xxxxxxxxxx'
DEFAULT_FROM_EMAIL: 'systems@mercycorps.org'
SERVER_EMAIL: "tola@mercycorps.org"
EMAIL_BACKEND: "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH: "/tmp/tola-messages"

DEV_APPS:
 - 'debug_toolbar'

DATABASES:
 default:
   ENGINE: "django.db.backends.mysql"
   NAME: "tola_activity"
   USER: "root"
   PASSWORD: "pass"
   OPTIONS: {"init_command": "SET default_storage_engine=MYISAM",}
   HOST: "localhost"
   PORT: ""

CACHES:
 default:
   BACKEND: "django.core.cache.backends.locmem.LocMemCache"


AUTHENTICATION_BACKENDS:
 # - 'social.backends.google.GoogleOAuth2'
 - 'social_core.backends.google.GoogleOAuth2'
 - 'django.contrib.auth.backends.ModelBackend'

# If report server then limit navigation and allow access to public dashboards
REPORT_SERVER: False
OFFLINE_MODE: False
NON_LDAP: True

TEMPLATE_DEBUG: False
DEBUG: True

EMAIL_HOST_PASSWORD: 'xxxxxxxxx'

# Google Analytics Tracking code
